apiVersion: v1
kind: Namespace
metadata:
  name: huawei-cloud-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huawei-cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-app: huawei-cloud-controller-manager
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: huawei-cloud-controller-manager
  template:
    metadata:
      labels:
        k8s-app: huawei-cloud-controller-manager
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      securityContext:
        runAsUser: 1001
      tolerations:
        - key: node.cloudprovider.kubernetes.io/uninitialized
          value: "true"
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      serviceAccountName: cloud-controller-manager
      containers:
        - name: huawei-cloud-controller-manager
          image: swr.ap-southeast-1.myhuaweicloud.com/k8s-cloudcontrollermanager/huawei-cloud-controller-manager:v0.19.14-alpha
          args:
            - /bin/huawei-cloud-controller-manager
            - --v=6
            - --cloud-config=/etc/config/cloud.conf
            - --cloud-provider=huaweicloud
            - --use-service-account-credentials=true
          volumeMounts:
            - mountPath: /etc/kubernetes
              name: k8s-certs
              readOnly: true
            - mountPath: /etc/ssl/certs
              name: ca-certs
              readOnly: true
            - mountPath: /etc/config
              name: cloud-config-volume
              readOnly: true
            - mountPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
              name: flexvolume-dir
          resources:
            requests:
              cpu: 200m
      hostNetwork: true
      volumes:
        - hostPath:
            path: /usr/libexec/kubernetes/kubelet-plugins/volume/exec
            type: DirectoryOrCreate
          name: flexvolume-dir
        - hostPath:
            path: /etc/kubernetes
            type: DirectoryOrCreate
          name: k8s-certs
        - hostPath:
            path: /etc/ssl/certs
            type: DirectoryOrCreate
          name: ca-certs
        - name: cloud-config-volume
          secret:
            secretName: cloud-config
